"""The protocol v2 wire layer: records, canonical bytes, and request identities.

A record is either exactly what the protocol declares or it is refused, the canonical encoding
of a record is one byte string and not a family of equivalent ones, and every identity is a
domain-separated hash over length-prefixed fields. The layers above hash what this one
produces, so this is where "the same value serializes the same way" has to be true. The one
part of this layer that touches a filesystem is the blob store, where an object is named by
the hash of its own bytes and reading it is a verification.

This is the only serving path. The version one one is retired, and the run directories it wrote
are read offline by :mod:`shogym.serve.v1_runs`.
"""

from shogym.serve.protocol_v2.blobs import (
    BLOB_DIRECTORY,
    BlobRef,
    BlobStore,
    FilesystemBlobStore,
    blob_ref,
    require_digest,
)
from shogym.serve.protocol_v2.errors import WireFormatError
from shogym.serve.protocol_v2.identity import (
    length_prefixed,
    presentation_request_identity,
    pull_request_identity,
    stream_message_id,
    submission_digest,
    terminal_request_identity,
)
from shogym.serve.protocol_v2.jcs import encode as canonical_json
from shogym.serve.protocol_v2.records import (
    AGENT_FILED,
    FLOOR_HORIZON,
    GRADED_HORIZON,
    HORIZON_ENDINGS,
    HORIZON_FILED,
    PROTOCOL_ERROR_CODES,
    PROTOCOL_VERSION,
    TERMINAL_SOURCES,
    Done,
    Payload,
    PresentationAck,
    PresentationCommit,
    ProtocolError,
    PullRequest,
    PullResult,
    Record,
    SealAck,
    SealReject,
    Task,
    TerminalMetadata,
    TerminalResult,
    Wait,
    canonical_bytes,
    decode_pull_result,
    decode_terminal_result,
    mcp_text_content,
    require_opaque_id,
    visible_bytes,
)
from shogym.serve.protocol_v2.schedule import (
    BY_ATTEMPT_ID,
    BY_POSITION,
    IMMEDIATE,
    NEVER,
    PAYLOAD_FIRST,
    PREDICATE_VERSION,
    RELEASE_AT_SEAL,
    RELEASE_NEVER,
    SCHEDULE_VERSION,
    TASK_FIRST,
    Assignment,
    EligibilityGate,
    ReleasePlan,
    ScheduleView,
    assignment_id_for,
    check_release,
    eligible_tasks,
    gate_open,
    order_key,
)

__all__ = [
    "AGENT_FILED",
    "BLOB_DIRECTORY",
    "BY_ATTEMPT_ID",
    "BY_POSITION",
    "FLOOR_HORIZON",
    "GRADED_HORIZON",
    "HORIZON_ENDINGS",
    "HORIZON_FILED",
    "IMMEDIATE",
    "NEVER",
    "PAYLOAD_FIRST",
    "PREDICATE_VERSION",
    "PROTOCOL_ERROR_CODES",
    "PROTOCOL_VERSION",
    "RELEASE_AT_SEAL",
    "RELEASE_NEVER",
    "SCHEDULE_VERSION",
    "TASK_FIRST",
    "TERMINAL_SOURCES",
    "Assignment",
    "BlobRef",
    "BlobStore",
    "Done",
    "EligibilityGate",
    "FilesystemBlobStore",
    "Payload",
    "PresentationAck",
    "PresentationCommit",
    "ProtocolError",
    "PullRequest",
    "PullResult",
    "Record",
    "ReleasePlan",
    "ScheduleView",
    "SealAck",
    "SealReject",
    "Task",
    "TerminalMetadata",
    "TerminalResult",
    "Wait",
    "WireFormatError",
    "assignment_id_for",
    "blob_ref",
    "canonical_bytes",
    "canonical_json",
    "check_release",
    "decode_pull_result",
    "decode_terminal_result",
    "eligible_tasks",
    "gate_open",
    "length_prefixed",
    "mcp_text_content",
    "order_key",
    "presentation_request_identity",
    "pull_request_identity",
    "require_digest",
    "require_opaque_id",
    "stream_message_id",
    "submission_digest",
    "terminal_request_identity",
    "visible_bytes",
]
