"""The named checks, and what each one is for.

Each check is named separately from the gates because failing it means something
different, so each is exercised on the ledger and, where a failure can be
constructed, on something that fails it.
"""

from __future__ import annotations

import pytest

from shogym.envs.receipts import admission, checks
from shogym.envs.receipts.generators.ledger import GENERATOR
from shogym.envs.receipts.protocol import draw
from shogym.envs.receipts.registry import load_generator

MASTER = bytes(range(32))
# Diagnostic bars, not the registered ones: loose enough that the fixture instance
# clears them, so a test about something else does not fail on a threshold.
THRESHOLDS = admission.Thresholds(
    max_copy_score=0.6, max_flip_score=0.95, min_leverage=0.05
)


def _instance(ordinal: int = 0):
    return draw(GENERATOR, MASTER, ordinal)


# ----- siblinghood -----


def test_every_axis_is_exercised_at_its_own_arity() -> None:
    """The exercise bar is min(3, arity), so a binary axis is asked for two."""
    result = checks.check_exercise(GENERATOR, _instance())
    assert result.passed, result.detail
    assert "boundary 2 of 2" in result.detail
    assert "anchor 3 of 3" in result.detail


def test_every_axis_moves_the_sibling_task() -> None:
    moved = checks.axis_materiality(GENERATOR, _instance())
    assert set(moved) == {"anchor", "basis", "boundary", "missing"}
    assert all(low >= 1 for low, _ in moved.values())
    assert checks.check_materiality(GENERATOR, _instance()).passed


def test_materiality_fails_an_axis_that_moves_too_few_rows() -> None:
    """The bar is exercised by raising it, because no shipped family has an inert axis.

    Every generator in this build moves at least one row of B on every option, so the
    failing side of `check_materiality` has no fixture to run on. Raising `min_rows`
    above the rows the axis actually moves exercises the same comparison, and the
    docstring says so rather than the test name promising coverage of a family whose
    B ignores an axis, which is coverage this suite does not have.
    """
    generator = load_generator("binary")
    instance = draw(generator, MASTER, 0)
    moved = checks.axis_materiality(generator, instance)
    assert moved["bin"][0] >= 1  # material, so the failure has to come from the bar
    assert checks.check_materiality(generator, instance, min_rows=1).passed is True
    failed = checks.check_materiality(generator, instance, min_rows=99)
    assert failed.passed is False
    assert "B is inert on bin" in failed.detail


# ----- the copy screen -----


def test_reusing_a_s_answers_earns_almost_nothing_on_b() -> None:
    """Identity and permutation transfer are worth nothing: B is a different table."""
    scores = checks.copy_scores(GENERATOR, _instance())
    assert set(scores) == set(checks.COPY_MAPS)
    assert scores["identity"] < 0.2
    assert scores["permutation"] < 0.2


def test_every_relabel_target_is_a_published_vocabulary() -> None:
    """A map into what B's drawn key happened to realize prices induction.

    Producing that filing means already knowing what the hidden draw did to B, which
    is the thing the screen exists to bound. It also made the copy verdict a property
    of the draw rather than of the surface pair. Every target side is the published
    answer order, so the relabel best is reachable from the two task texts alone.
    """
    instance = _instance()
    published = set(GENERATOR.answer_ranks(instance.b.table))
    realized = set(instance.b.key)
    assert realized <= published
    for filing in checks.copy_map_filings(GENERATOR, instance)["relabel"]:
        assert set(filing) <= published | set(instance.a.key) | {""}


def test_the_registered_row_moves_are_closed_under_composition() -> None:
    """A LIST OF GENERATORS IS NOT THE FAMILY, and this asserts the difference.

    The registered row moves are generated by the rotation and the reversal. An
    enumeration that listed those two without their compositions left out every
    reversal followed by a rotation, and the containment and product-size checks below
    passed on it: they say the family holds its parts, not that it holds their
    compositions. This composes every pair of moves on unique row markers and requires
    the result to be a member.
    """
    markers = tuple(f"r{n:02d}" for n in range(24))
    moves = [tuple(move) for move in checks._permutations(list(markers), len(markers))]
    assert len(moves) == len(set(moves)) == 48  # the dihedral group on 24 positions

    # Each move as the positions it reads from, so it can be applied to any sequence.
    order = {move: tuple(markers.index(marker) for marker in move) for move in moves}

    def apply(move, sequence):
        return tuple(sequence[position] for position in order[move])

    members = set(moves)
    for first in moves:
        for second in moves:
            assert apply(second, apply(first, markers)) in members


def test_the_registered_token_maps_are_closed_under_composition() -> None:
    """The token factor, asserted the way the row factor is.

    Each registered dictionary is applied by leaving anything outside it alone, so it
    is a total function on the tokens the dictionaries and the filing mention, and two
    of them compose into a third. Listing the dictionaries and not their compositions
    left such a map out, and one of those scored 13 of 24 on a draw whose reported
    maximum was 11 of 24.
    """
    instance = _instance(7)
    values = list(instance.a.key)
    source_ranks = GENERATOR.answer_ranks(instance.a.table)
    target_ranks = GENERATOR.answer_ranks(instance.b.table)
    maps = checks._token_maps(values, source_ranks, target_ranks)
    universe = sorted(set(values) | set(source_ranks) | set(target_ranks))

    def total(table):
        return tuple(table.get(token, token) for token in universe)

    members = {total(table) for table in maps}
    assert len(members) == len(maps)  # no member is listed twice
    assert tuple(universe) in members  # the identity is one of them

    position = {token: n for n, token in enumerate(universe)}
    for first in members:
        for second in members:
            composed = tuple(second[position[image]] for image in first)
            assert composed in members

    # And closing again finds nothing, so what the screen prices is a fixed point.
    again = checks._token_maps(values, source_ranks, target_ranks)
    assert {total(table) for table in again} == members


def test_the_whole_registered_copy_family_is_closed() -> None:
    """ONE PROPERTY OVER THE WHOLE FAMILY, so an unclosed addition fails loudly.

    Three times a registered family was enumerated from its generators rather than
    closed: first the row moves without their compositions, then the token maps
    without theirs. Product size and sub-family containment pass on both, because they
    say the family holds its parts and not their compositions. This says the thing
    that was false: applying any registered transformation to any registered filing
    lands on a registered filing.

    It runs on a small vocabulary rather than a ledger draw so the whole product can
    be walked exhaustively. What it checks is the construction, which does not know
    how many rows or bands a family has.
    """
    values = ["low", "mid", "high", "low", "mid", "high"]
    source_ranks = ["low", "mid", "high"]
    target_ranks = ["one", "two", "three"]
    width = len(values)

    token_maps = checks._token_maps(values, source_ranks, target_ranks)
    relabels = checks._relabellings(values, source_ranks, target_ranks, width)
    family = checks._distinct(
        filing
        for relabelled in relabels
        for filing in checks._permutations(relabelled, width)
    )
    members = {tuple(filing) for filing in family}
    assert len(members) == len(family) > len(relabels)

    # Every registered transformation, as it is actually applied: a token map on the
    # values, and a row move on the positions.
    markers = [f"p{n}" for n in range(width)]
    orders = [
        tuple(markers.index(marker) for marker in move)
        for move in checks._permutations(markers, width)
    ]
    for filing in family:
        for table in token_maps:
            relabelled = [table.get(value, value) for value in filing]
            for order in orders:
                moved = tuple(relabelled[position] for position in order)
                assert moved in members


def test_the_registered_copy_family_is_closed_under_composition() -> None:
    """The bar is read against a family, and this one is closed.

    Relabelling A's answers and permuting the rows are the two registered moves. They
    act on different things, so they commute and composing them in either order
    generates nothing further; enumerating each alone reported a maximum no map in the
    family could reach. The three named maps are sub-families of the closure and are
    printed for diagnosis, so a failure says which cheap map did it.
    """
    instance = _instance()
    filings = checks.copy_map_filings(GENERATOR, instance)
    # Exhaustive: every relabelling under every permutation, and nothing dropped.
    assert len(filings["closure"]) == len(filings["relabel"]) * len(
        filings["permutation"]
    )
    for name in checks.REPORTED_MAPS:
        assert all(filing in filings["closure"] for filing in filings[name]), name
    scores = checks.copy_scores(GENERATOR, instance)
    assert scores["closure"] >= max(scores[name] for name in checks.REPORTED_MAPS)
    assert "closure" in checks.NO_INDUCTION_MAPS
    assert "option_flip" not in checks.NO_INDUCTION_MAPS
    result = checks.check_copy(
        GENERATOR, instance, admission.REGISTERED_MAX_COPY_SCORE, 0.875, 0.1
    )
    assert "over the closed family" in result.detail
    assert "alone: identity" in result.detail


def test_a_draw_a_composed_token_map_copies_is_excluded() -> None:
    """The draw the unclosed token family admitted, kept as the regression.

    Its rank map carries A's bands into B's and leaves an untouched token alone; its
    filed map carries that token onward and leaves the already translated bands alone.
    Both are registered dictionaries, and their composition, reversed and rotated, is
    a filing an agent builds from A's answers and B's published vocabulary alone. It
    earns 13 of 24, where the enumeration that listed the dictionaries and not their
    compositions reported 11 of 24 and the bar admitted it.
    """
    instance = _instance(7)
    scores = checks.copy_scores(GENERATOR, instance)
    assert scores["closure"] == round(13 / 24, 6)
    assert max(scores[name] for name in checks.REPORTED_MAPS) <= 0.5
    report = admission.report(GENERATOR, instance, MASTER, admission.Thresholds())
    assert report.gates.verdict  # the copy screen excludes it, not a gate
    assert report.failed_checks == ("copy",)
    assert not report.admitted


def test_a_draw_a_composed_row_move_copies_is_excluded() -> None:
    """The draw the incomplete enumeration admitted, kept as the regression.

    Its relabel alone earns 0.3333 and every listed row move alone earns nothing, so
    an enumeration without the compositions reported 0.5000 and the bar admitted it.
    A reversal followed by a rotation of the same relabel earns 0.5417, which is over
    the bar, and it is built from A's answers and B's published rows alone.
    """
    instance = _instance(43)
    scores = checks.copy_scores(GENERATOR, instance)
    assert scores["closure"] == round(13 / 24, 6)
    assert max(scores[name] for name in checks.REPORTED_MAPS) <= 0.5
    report = admission.report(GENERATOR, instance, MASTER, admission.Thresholds())
    assert report.gates.verdict  # it is the copy screen that excludes it, not a gate
    assert report.failed_checks == ("copy",)
    assert not report.admitted


def test_the_copy_bar_is_read_against_the_closure_and_not_a_sub_family() -> None:
    """A bar and the maps it is a maximum over are one registration.

    This instance's relabel alone is under the registered bar and its closure is over
    it, so a screen that stopped at the sub-families would admit an instance a cheap
    composed map copies.
    """
    instance = _instance()
    scores = checks.copy_scores(GENERATOR, instance)
    bar = admission.REGISTERED_MAX_COPY_SCORE
    assert max(scores[name] for name in checks.REPORTED_MAPS) <= bar < scores["closure"]
    failed = checks.check_copy(GENERATOR, instance, bar, 0.875, 0.1)
    assert not failed.passed
    assert "through closure" in failed.detail


def test_each_copy_map_is_optimized_over_its_own_family() -> None:
    """A screen that tried one rotation would report the wrong number."""
    filings = checks.copy_map_filings(GENERATOR, _instance())
    assert len(filings["permutation"]) > 2
    assert len(filings["relabel"]) > 1
    # the ledger has 12 wrong options across its four axes
    assert len(filings["option_flip"]) == 2 + 2 + 1 + 3


def test_getting_one_axis_wrong_is_scored_separately_from_copying() -> None:
    """Producing an option flip means having induced every other axis, so it is not
    transfer and it does not share transfer's threshold."""
    scores = checks.copy_scores(GENERATOR, _instance())
    assert scores["option_flip"] > max(
        scores[name] for name in checks.NO_INDUCTION_MAPS
    )
    assert "option_flip" not in checks.NO_INDUCTION_MAPS


def test_the_two_copy_thresholds_bind_independently() -> None:
    instance = _instance()
    assert checks.check_copy(GENERATOR, instance, 0.6, 0.95, 0.05).passed
    tight_copy = checks.check_copy(GENERATOR, instance, 0.01, 0.95, 0.05)
    assert not tight_copy.passed and "reusing A's answers" in tight_copy.detail
    tight_flip = checks.check_copy(GENERATOR, instance, 0.6, 0.10, 0.05)
    assert not tight_flip.passed and "one axis wrong" in tight_flip.detail
    weak = checks.check_copy(GENERATOR, instance, 0.6, 0.95, 0.99)
    assert not weak.passed and "pays too little" in weak.detail


def test_every_axis_carries_positive_leverage_on_b() -> None:
    leverage = checks.axis_leverage(GENERATOR, _instance())
    assert set(leverage) == {"anchor", "basis", "boundary", "missing"}
    assert all(value > 0.0 for value in leverage.values()), leverage


# ----- the artifact invariants -----


def test_the_instance_rebuilds_identically() -> None:
    assert checks.check_fixation(GENERATOR, _instance(), MASTER).passed


def test_a_rebuild_under_another_key_is_not_the_same_instance() -> None:
    result = checks.check_fixation(GENERATOR, _instance(), bytes(range(1, 33)))
    assert not result.passed


def test_the_envelope_holds_over_the_whole_convention_support() -> None:
    result = checks.check_envelope(GENERATOR, _instance())
    assert result.passed, result.detail
    assert "over all 72 conventions" in result.detail


def test_neither_task_text_names_an_option() -> None:
    for ordinal in range(4):
        assert checks.check_lint(GENERATOR, _instance(ordinal)).passed


def test_the_task_texts_are_identical_under_every_convention() -> None:
    result = checks.check_invariance(GENERATOR, _instance())
    assert result.passed, result.detail


# ----- admission -----


def test_admission_runs_every_gate_and_every_check() -> None:
    report = admission.report(GENERATOR, _instance(), MASTER, THRESHOLDS)
    assert report.gates.verdict
    assert [c.name for c in report.checks] == [
        "exercise", "materiality", "copy", "fixation", "envelope", "graded", "placebo",
        "neutral", "oracle", "lint", "invariance",
    ]
    assert report.admitted
    assert "ADMITTED" in "\n".join(report.lines())


def test_a_failing_check_excludes_an_instance_even_when_the_gates_pass() -> None:
    tight = admission.Thresholds(max_copy_score=0.0, max_flip_score=0.95, min_leverage=0.05)
    report = admission.report(GENERATOR, _instance(), MASTER, tight)
    assert report.gates.verdict
    assert report.failed_checks == ("copy",)
    assert not report.admitted


def test_the_gate_version_is_named_and_excludes_the_count_gate() -> None:
    assert admission.GATE_VERSION == "receipts-gates-v2"


def test_the_bars_are_registered_and_overridable() -> None:
    """They have values because someone chose them against a measured distribution.

    A bank record carries no bars at all; the bundle stores the registered set and
    refuses to verify against any other, so an override is diagnostic and leaves
    nothing durable behind it."""
    registered = admission.Thresholds()
    assert registered.registered
    assert registered.min_headroom == admission.REGISTERED_MIN_HEADROOM == 0.05
    assert registered.max_copy_score == admission.REGISTERED_MAX_COPY_SCORE == 0.50
    assert registered.max_flip_score == admission.REGISTERED_MAX_FLIP_SCORE == 0.875
    assert registered.min_leverage == admission.REGISTERED_MIN_LEVERAGE == 0.10
    assert not admission.Thresholds(max_copy_score=0.9).registered
    with pytest.raises(ValueError):
        admission.Thresholds(max_copy_score=float("nan"))


# ----- the registered bars, against the ledger's own distribution -----


def test_the_registered_bars_fill_a_bank() -> None:
    """The structural facts the bars were chosen against, checked on a small bank.

    The ledger's one-axis-wrong score is never below five sixths, so a flip bar under
    that admits nothing and 0.875 keeps the draws that are not the worst. Its weakest
    axis leverage never exceeds one sixth, so a leverage bar above that admits nothing
    and 0.10 sits under the ceiling. Together the bars have to leave enough supply to
    fill a bank, and that is what this asserts rather than any particular yield.
    """
    from shogym.envs.receipts import bank as bank_mod

    registered = admission.Thresholds()
    built = bank_mod.materialize(GENERATOR, MASTER, 4)
    found = bank_mod.population(built, GENERATOR)
    assert built.size == 4
    assert len(found.instances) == 4
    assert found.considered >= 4
    assert registered.max_flip_score == 0.875
    assert registered.min_leverage == 0.10


def test_every_admitted_instance_clears_every_registered_bar() -> None:
    registered = admission.Thresholds()
    admitted = 0
    for ordinal in range(12):
        instance = draw(GENERATOR, MASTER, ordinal)
        report = admission.report(GENERATOR, instance, MASTER, registered)
        if not report.admitted:
            continue
        admitted += 1
        assert report.gates.headroom > registered.min_headroom
        scores = checks.copy_scores(GENERATOR, instance)
        plain = max(scores[name] for name in checks.NO_INDUCTION_MAPS)
        assert plain <= registered.max_copy_score
        assert scores["option_flip"] <= registered.max_flip_score
        assert min(checks.axis_leverage(GENERATOR, instance).values()) >= (
            registered.min_leverage
        )
    assert admitted, "the registered bars admitted nothing in twelve draws"


def test_the_bars_bite_where_the_distribution_says_they_do() -> None:
    """A flip bar below five sixths empties the sample; a leverage bar above one
    sixth does the same. Both are the structural facts the middle set sits between."""
    registered = admission.Thresholds()
    flips: list[float] = []
    leverages: list[float] = []
    for ordinal in range(8):
        instance = draw(GENERATOR, MASTER, ordinal)
        flips.append(checks.copy_scores(GENERATOR, instance)["option_flip"])
        leverages.append(min(checks.axis_leverage(GENERATOR, instance).values()))
    # The component score is rounded to six places, which is registered, so five
    # sixths appears as 0.833333 and the comparison is made at that rounding.
    assert min(flips) >= round(5 / 6, 6)
    assert max(leverages) <= round(1 / 6, 6)
    assert registered.max_flip_score > 5 / 6
    assert registered.min_leverage < 1 / 6


def test_a_bank_is_filled_under_the_registered_bars_or_not_at_all() -> None:
    """A caller's loosened bars are refused, not honoured.

    `settled` is the gate set's own constants, R's arity and blocks and H's headroom.
    The named checks' bars are outside it, so a set that moved copy, flip and leverage
    is settled and not registered, and a bank could once be filled under it. Every bar
    is what admitted the instances, so every bar is what a bank is filled under.
    """
    from shogym.envs.receipts import bank as bank_mod

    loose = admission.Thresholds(max_copy_score=0.9, max_flip_score=0.99,
                                 min_leverage=0.01)
    assert loose.settled and not loose.registered
    # And a moved H bar is not settled either: H is part of what the gate name means.
    assert not admission.Thresholds(min_headroom=0.0).settled
    built = bank_mod.materialize(GENERATOR, MASTER, 1)
    with pytest.raises(ValueError, match="only the registered bars may fill a bank"):
        bank_mod.population(built, GENERATOR, loose)
    # The population is a function of the registered rule, not of a caller's bars.
    assert bank_mod.population(built, GENERATOR).ordinals == bank_mod.population(
        built, GENERATOR, admission.Thresholds()
    ).ordinals


def test_the_admission_report_carries_the_bars_it_judged_against() -> None:
    instance = draw(GENERATOR, MASTER, 0)
    registered = admission.report(GENERATOR, instance, MASTER, admission.Thresholds())
    loose = admission.report(
        GENERATOR, instance, MASTER, admission.Thresholds(max_copy_score=0.9)
    )
    assert registered.thresholds.registered
    assert registered.digest() != loose.digest()
