"""What "reusing A's answers on B" means for one family, and which family means which.

THE COPY SCREEN PRICES A FAMILY OF MAPS, and the family is a property of what a task
publishes rather than of the screen. Ledger publishes a complete ordered vocabulary of
whole row answers: the band table each sibling prints, in the order it prints it. The
cheapest transfer there is to read both tables off the two task texts and send first to
first, so the registered maps are dictionaries between two published orders, closed
under composition. Sound change publishes no such vocabulary. It publishes a phoneme
alphabet and a word grammar, and a whole daughter form is not a token of an ordered
list: returning the daughters B's drawn key realized would price a transfer nobody can
perform, because producing that list means already knowing what the draw did to B, and
enumerating every legal word up to sixteen phones is not a list either. Its registered
maps are global character maps instead: every permutation of the three deletable vowels
and every permutation of the three replacement phones, applied to A's correct daughters.

SO THE PROFILE IS DECLARED, NOT INFERRED. A generator declares `COPY_PROFILE` and
`registry.load_generator` refuses one that does not, because the failure a default
would produce is silent: a family whose answers are words, priced under the token
profile, reports the maximum of a family of maps that cannot be built, and the bar is
read against a number that measured nothing. A profile this module does not know is
refused for the same reason.

THE BAR AND THE FAMILY ARE ONE REGISTRATION. A screen that enumerates more maps reports
a larger maximum whether or not the extra maps are a real channel, so a number measured
against one family means nothing held against another. `soundchange_v1` and its 0.50
bar are a NEW registration under the gate label this build publishes; 0.50 is carried
over as a conservative initial ceiling and inherits none of the ordered-token profile's
empirical calibration.

BOTH FAMILIES ARE CLOSED under composition, which is why each is a family and not a
list. The row moves are generated by the rotation and the reversal, so their closure is
the dihedral group: every rotation of the sequence and of its reversal, 48 moves at 24
rows. The ordered-token maps are the registered dictionaries and every composition of
them, computed generically rather than listed. The character maps are the product of
two symmetric groups on disjoint letter sets, which is closed as it stands. Token and
character maps act on values and row moves on positions, so the two commute, and a
product of two commuting closed families is closed.
"""

from __future__ import annotations

import itertools
from typing import Iterable, Mapping, Sequence

#: The declared profiles. A generator names one of these and nothing else.
ORDERED_TOKENS = "ordered_tokens"
SOUNDCHANGE_V1 = "soundchange_v1"
PROFILES = (ORDERED_TOKENS, SOUNDCHANGE_V1)

#: Which profiles consume the family's published answer ranks. A profile that does not
#: is the reason `answer_ranks` may return None: an empty tuple would be a fictitious
#: complete vocabulary, and a screen built over it would report a maximum of nothing.
CONSUMES_RANKS = {ORDERED_TOKENS: True, SOUNDCHANGE_V1: False}

#: The letters the sound change character maps permute among themselves: the three
#: vowels the deletion pass can remove, and the three phones the replacement pass can
#: introduce. Every other character is fixed, so the map is a relabelling of exactly
#: the symbols whose identity the hidden rule chooses.
DELETABLE_VOWELS = ("a", "e", "i")
REPLACEMENT_PHONES = ("g", "x", "s")


def profile_of(generator) -> str:
    """The copy profile this generator declares, refused when it declares none.

    Refused rather than defaulted. A default is a decision about what a family's
    answers are, taken by whoever wrote this module about a family they have not seen.
    """
    declared = getattr(generator, "COPY_PROFILE", None)
    name = getattr(generator, "name", type(generator).__name__)
    if declared is None:
        raise ValueError(
            f"{name!r} declares no COPY_PROFILE. The copy screen prices a registered "
            f"family of maps and the bar is read against exactly that family, so a "
            f"generator says which one its answers are; the declared profiles are "
            f"{', '.join(PROFILES)}"
        )
    if declared not in PROFILES:
        raise ValueError(
            f"{name!r} declares copy profile {declared!r}; the registered profiles are "
            f"{', '.join(PROFILES)}"
        )
    return str(declared)


def require_profile(generator):
    """Refuse a generator that does not declare a registered profile. Returns it."""
    profile_of(generator)
    return generator


def answer_ranks_for(generator, table) -> tuple[str, ...] | None:
    """The family's published answer order, or None where the profile consumes none.

    A rank profile that returns None has no published vocabulary and cannot be priced
    by maps between two of them; a non-rank profile that returns a list has published
    one and should be priced by them. Either way the declaration and the callback
    disagree, which is refused here rather than turned into a smaller maximum.
    """
    profile = profile_of(generator)
    ranks = generator.answer_ranks(table)
    if CONSUMES_RANKS[profile]:
        if ranks is None:
            raise ValueError(
                f"{generator.name!r} declares the {profile!r} profile and publishes no "
                "answer ranks, so the transfer its bar is read against cannot be built"
            )
        return tuple(ranks)
    if ranks is not None:
        raise ValueError(
            f"{generator.name!r} declares the {profile!r} profile, which consumes no "
            "answer ranks, and returned some; a family that publishes a complete "
            "ordered vocabulary is priced by the maps between two of them"
        )
    return None


# --------------------------------------------------------------------------
# positional moves, shared by every profile
# --------------------------------------------------------------------------


def fit(values: Sequence[str], width: int) -> list[str]:
    """A filing for B of the right length, whatever A's row count was."""
    padded = list(values) + [""] * width
    return padded[:width]


def distinct(filings: Iterable[Sequence[str]]) -> list[list[str]]:
    """The same filings with the repeats dropped, in the order they first appeared.

    A closed family names one filing many ways: the row move that undoes a rotation of
    a symmetric filing, the two maps that agree on the answers A actually filed.
    Scoring each of those again costs a parse and decides nothing, and the maximum is
    over the set rather than over the enumeration.
    """
    seen: dict[tuple[str, ...], list[str]] = {}
    for filing in filings:
        seen.setdefault(tuple(filing), list(filing))
    return list(seen.values())


def permutations(values: Sequence[str], width: int) -> list[list[str]]:
    """The registered row moves, as the CLOSED family the two generators produce.

    The generators are the rotation and the reversal, and a family that listed only
    those was not closed: reversing and THEN rotating is a composition of registered
    moves that no listed member equals, and on a real draw one of them scored above the
    bar while the reported maximum sat under it. Rotation and reversal generate the
    dihedral group, so the closed family is every rotation of the sequence and every
    rotation of the reversed sequence: 2n moves for n rows, 48 at 24.

    The moves are positional, so they are taken on the FITTED sequence: the filing they
    rearrange is the one B would receive, whatever A's row count was.
    """
    fitted = fit(values, width)
    reversed_fitted = list(reversed(fitted))
    out: list[list[str]] = []
    for base in (fitted, reversed_fitted):
        for shift in range(max(len(base), 1)):
            out.append(list(base[shift:]) + list(base[:shift]))
    return out


# --------------------------------------------------------------------------
# the ordered-token profile
# --------------------------------------------------------------------------


def token_generators(
    values: Sequence[str],
    source_ranks: Sequence[str],
    target_ranks: Sequence[str],
) -> list[dict[str, str]]:
    """The registered token dictionaries themselves, before anything is closed.

    EVERY TARGET SIDE IS A PUBLISHED VOCABULARY. The RANK map takes the two tasks' own
    published answer orders and sends first to first: it is the cheapest transfer there
    is, because both orders are printed in the two task texts and reading them off
    needs no induction at all. Its rotations come with it. The LEXICAL map is the same
    construction over the published vocabularies sorted alphabetically, which is what a
    reader with no sense of the order would write. The FILED map narrows the source to
    the answers the agent actually filed on A, which it knows without inducing
    anything, and sends them into the same published target order.

    The target side is never the tokens B's drawn key happened to realize. A map into
    the realized target prices a transfer nobody could perform: producing it means
    already knowing what the hidden draw did to B, which is the thing the screen exists
    to bound. It is also not measuring the surface pair, since it moves with the draw,
    and the bar was read against the numbers it inflated.

    These are the GENERATORS. What the screen is read against is what they generate,
    which `token_maps` computes.
    """
    out: list[dict[str, str]] = []
    # AN EMPTY VALUE IS NOT AN ANSWER THE AGENT FILED. A reduced filing holds a value
    # at the rows the receipt reported and nothing at the rest, and the empty positions
    # are rows the reader has no token for. Counting the absence as a filed answer would
    # register a map that carries it into a published band, which credits the reader
    # with a value at a row it knows nothing about.
    filed = sorted(token for token in set(values) if token)
    for source, into in (
        (list(source_ranks), list(target_ranks)),
        (sorted(set(source_ranks)), sorted(set(target_ranks))),
        (filed, sorted(set(target_ranks))),
    ):
        if not source or not into:
            continue
        for shift in range(len(into)):
            out.append({s: into[(i + shift) % len(into)] for i, s in enumerate(source)})
    return out


def token_maps(
    values: Sequence[str],
    source_ranks: Sequence[str],
    target_ranks: Sequence[str],
) -> list[dict[str, str]]:
    """The registered token dictionaries CLOSED under composition, identity first.

    A LIST OF DICTIONARIES IS NOT THE FAMILY, and the difference has a price. Each
    registered dictionary is applied by leaving anything outside it alone, so it is a
    total function on the finite set of tokens the dictionaries and the filing mention,
    and two of them compose into a third total function on that same set. A rank map
    that carries A's bands into B's while leaving an untouched token alone, followed by
    a filed map that carries that token onward while leaving the already translated
    bands alone, is a map an agent builds from the same two published dictionaries and
    no more. Listing the dictionaries and not their compositions left such a map out,
    and on a real draw it scored 13 of 24 where the reported maximum was 11 of 24, so
    the bar admitted it.

    So this closes them, generically rather than by hand. Compositions are taken until
    no new map appears, which terminates because there are finitely many functions from
    a finite token set to itself. The result is a monoid: the identity is in it, and it
    is closed, so nothing an agent can build by chaining registered dictionaries is
    outside what the screen prices.
    """
    # AN EMPTY VALUE IS NOT A TOKEN ANY PUBLISHED VOCABULARY CARRIES, so no registered
    # map moves it and it is not in the set the maps are closed over. A filing that
    # holds nothing at a row is a row the reader has no token for; putting that absence
    # in the universe would price maps that carry it into a band, which is a map nobody
    # can build from two printed lists, and it would close the family over a point the
    # generators only ever map out of. The reduced-receipt diagnostic files exactly such
    # a filing, and with the absence in the universe its closure runs to tens of
    # thousands of maps on a family whose two vocabularies are the same six tokens.
    universe = sorted(token for token in
                      set(values) | set(source_ranks) | set(target_ranks) if token)
    if not universe:
        return [{}]
    position = {token: n for n, token in enumerate(universe)}

    def total(table: Mapping[str, str]) -> tuple[str, ...]:
        """One dictionary as its images over the whole token set, in one order."""
        return tuple(table.get(token, token) for token in universe)

    def after(first: tuple[str, ...], second: tuple[str, ...]) -> tuple[str, ...]:
        """`first` and then `second`, which is a map on the same token set."""
        return tuple(second[position[image]] for image in first)

    identity = tuple(universe)
    found = [identity]
    known = {identity}
    for table in token_generators(values, source_ranks, target_ranks):
        made = total(table)
        if made not in known:
            known.add(made)
            found.append(made)
    frontier = list(found)
    while frontier:
        fresh: list[tuple[str, ...]] = []
        against = list(found)
        for one in frontier:
            for other in against:
                for made in (after(one, other), after(other, one)):
                    if made not in known:
                        known.add(made)
                        found.append(made)
                        fresh.append(made)
        frontier = fresh
    return [dict(zip(universe, image)) for image in found]


def token_relabellings(
    values: Sequence[str],
    source_ranks: Sequence[str],
    target_ranks: Sequence[str],
    width: int,
) -> list[list[str]]:
    """Every filing the closed token family can make of A's answers, deduplicated.

    The identity is among the maps, so the untouched filing leads the list and
    composing this with the row moves produces those moves themselves.

    THE ORBIT OF THE FILING, NOT THE MONOID OF MAPS, and the two give the same set. A
    composition applied to a filing is the first dictionary applied to it and then the
    next, so closing the FILINGS under the registered dictionaries reaches exactly what
    closing the dictionaries first and applying each would. What it does not do is build
    the monoid: where two published vocabularies are the same six tokens and one
    registered dictionary is not injective, that monoid runs to tens of thousands of
    maps which between them make a few dozen filings, and closing it took a quarter of
    an hour on one reduced filing. `token_maps` remains the statement of what the family
    IS, and this is the family as it reaches a filing.
    """
    generators = token_generators(values, source_ranks, target_ranks)
    start = list(values)
    reached: dict[tuple[str, ...], list[str]] = {tuple(start): start}
    frontier = [start]
    while frontier:
        fresh: list[list[str]] = []
        for filing in frontier:
            for table in generators:
                made = [table.get(value, value) for value in filing]
                if tuple(made) not in reached:
                    reached[tuple(made)] = made
                    fresh.append(made)
        frontier = fresh
    seen: dict[tuple[str, ...], list[str]] = {}
    for filing in reached.values():
        fitted = fit(filing, width)
        seen.setdefault(tuple(fitted), fitted)
    return list(seen.values())


# --------------------------------------------------------------------------
# the sound change profile
# --------------------------------------------------------------------------


def character_maps() -> list[dict[str, str]]:
    """The registered global character maps: 36, identity first.

    Every permutation of the three deletable vowels crossed with every permutation of
    the three replacement phones, every other character fixed. The two letter sets are
    disjoint, so the product is the direct product of two symmetric groups and is
    closed under composition as it stands.

    WHY THESE LETTERS. They are the symbols the hidden rule names. A reader holding A's
    corrected key can see which phone replaced k and which vowel went missing, and the
    cheap thing to try on B is the same daughter with those identities swapped for the
    ones it guesses. A wider family of arbitrary character bijections would price maps
    that turn one form's inert consonants into another's, which is what the analogy
    check prices separately and by its own construction rather than by relabelling.
    """
    out: list[dict[str, str]] = []
    for vowels in itertools.permutations(DELETABLE_VOWELS):
        for phones in itertools.permutations(REPLACEMENT_PHONES):
            table: dict[str, str] = dict(zip(DELETABLE_VOWELS, vowels))
            table.update(zip(REPLACEMENT_PHONES, phones))
            out.append(table)
    return out


def apply_characters(table: Mapping[str, str], value: str) -> str:
    """One character map applied to one whole value, character by character."""
    return "".join(table.get(character, character) for character in value)


def character_relabellings(values: Sequence[str], width: int) -> list[list[str]]:
    """Every filing the closed character family can make of A's answers, deduplicated.

    The identity map leads, so the untouched filing leads the list and composing this
    with the row moves produces those moves themselves.
    """
    seen: dict[tuple[str, ...], list[str]] = {}
    for table in character_maps():
        filing = fit([apply_characters(table, value) for value in values], width)
        seen.setdefault(tuple(filing), filing)
    return list(seen.values())


# --------------------------------------------------------------------------
# the dispatch
# --------------------------------------------------------------------------


def relabellings(
    generator, instance, values: Sequence[str], width: int
) -> list[list[str]]:
    """Every filing this family's registered value maps can make of A's answers.

    Dispatched on the DECLARED profile, so a family whose answers are words is never
    priced by maps between two published vocabularies it does not have, and a family
    that has them is never priced by character maps that mean nothing to it.
    """
    profile = profile_of(generator)
    if profile == ORDERED_TOKENS:
        source = answer_ranks_for(generator, instance.a.table)
        target = answer_ranks_for(generator, instance.b.table)
        return token_relabellings(values, source or (), target or (), width)
    if profile == SOUNDCHANGE_V1:
        answer_ranks_for(generator, instance.a.table)
        answer_ranks_for(generator, instance.b.table)
        return character_relabellings(values, width)
    raise ValueError(f"no copy family is registered for profile {profile!r}")


__all__ = [
    "CONSUMES_RANKS",
    "DELETABLE_VOWELS",
    "ORDERED_TOKENS",
    "PROFILES",
    "REPLACEMENT_PHONES",
    "SOUNDCHANGE_V1",
    "answer_ranks_for",
    "apply_characters",
    "character_maps",
    "character_relabellings",
    "distinct",
    "fit",
    "permutations",
    "profile_of",
    "relabellings",
    "require_profile",
    "token_generators",
    "token_maps",
    "token_relabellings",
]
