"""The durable protocol v2 kernel: one stream generation as a Temporal workflow.

This package is where Temporal is imported, and nothing outside it imports Temporal. A
quickstart install has it, because serving is what the package is for, and the runner starts
its own embedded service, so a user never installs or runs a server.

What is here is the generic kernel: a typed pull, a durable seal before any acknowledgement,
offers and presentations against a harness cursor, a schedule model, and a monotonic Done. A
generation carries an immutable assignment roster and one release plan. Immediate makes an
obligation eligible at the seal of the attempt it belongs to, Never creates no obligation at
all, and a plan may gate a named task on a payload being presented or on another task sealing.
The experimental schedule is not here: no leg automata, payload families, fork, or retry scopes,
and no delayed release, blocked obligations, or end-of-queue tail policies.

A generation also carries what it delivers. Every payload obligation is resolved before anything
is served, per obligation and per branch, either to a payload policy and a cell or to a
withholding and a reason. An ordinary run resolves to the honest policy, whose body reports the
score the seal committed; a run that conceals or replaces that registers the policy it wants and
is recorded as having done so. A generation that has resolved nothing is not started.

The Python API a gateway calls
------------------------------

Start a service and a Worker. ``run_directory`` is the run this service is for, and the history
it writes goes there, beside that run's blobs and manifest. A client opened without one gets a
database that goes when the process does, which is the right answer for a stream nobody will
take over and the wrong one for every other::

    async with durable_client(run_directory=run) as client:
        async with stream_worker(client):
            ...

Start a stream. :class:`~shogym.serve.protocol_v2.kernel.messages.StreamStart` carries the
closed queue with every public identifier preallocated, the capacity, the consumer claim hash,
the initial cursor, and the terminal tool::

    stream = await start_stream(client, start, workflow_id="stream/run-1/gen-1")
    await stream.claim_consumer(ConsumerClaim(consumer_id=..., claim_hash=...))

Starting is a claim of ownership, and so is taking a generation over after the process that was
serving it went away. The client that takes it over is opened against that run's directory,
because the history the last process wrote is what is being resumed and that is where it is::

    async with durable_client(run_directory=run) as client:
        stream = await resume_stream(client, workflow_id="stream/run-1/gen-1",
                                     configuration_hash=configuration_hash(start))

That fences the previous writer. Its handle keeps the epoch it had, and every call it makes
from then on is refused without touching the stream, including one that was already in flight.
A claim that presents a different configuration hash is refused instead, and nothing moves.
:func:`resume_run_directory` does the same from a directory, deriving that hash from the
composition the resuming process serves rather than reading it back out of the manifest. It is
also where a protocol v1 run is refused before anything is claimed at all.

An active attempt the generation has since authorized a call to a world for is one whose world
has moved past the checkpoint it would come back from, and taking it over means saying so. The
claim carries ``restored_checkpoints``, the attempts this owner put back and the checkpoint it
put each of them back from, and a claim that says nothing about such an attempt is refused with
``invalid_attempt`` and nothing touched. What has to be named, and what to name it under, are
``restoration_required`` and ``task_checkpoints`` in the state Query.

Then the loop. A pull returns one
:class:`~shogym.serve.protocol_v2.kernel.messages.OfferedMessage`, whose ``visible_text`` is
the exact canonical bytes to put in front of the model. Nothing advances until the harness has
written those bytes and said so::

    message = await stream.pull(PullRequest(request_id=..., last_presented_cursor=cursor))
    ack = await stream.present(message, attestation_id=..., transcript_blob=...,
                               task_start_checkpoint_blob=...)
    cursor = ack.cursor

A Task presentation must carry the task-start checkpoint it can be restored from. When the
model files, the gateway intercepts the terminal call and seals::

    result = await stream.seal(SealRequest(metadata=..., public_tool_name=...,
                                           native_terminal_name=..., native_arguments=...))

That returns a SealAck, or a SealReject when the native arguments do not match the declared
schema, which leaves the attempt exactly where it was. An acknowledgement is presented like
any other result, but it is the last result of a completed provider turn, so its presentation
carries the provider-turn blob and says the turn completed. The next pull is refused until it
does. When the queue is closed and everything has been sealed, acknowledged, and delivered, a
pull returns Done, and presenting Done ends the generation.

An attempt nobody is going to finish is ended by the controller instead::

    await stream.finalize(FinalizeRequest(attempt_id=..., reason=STEP_CAP))

That mints nothing the model can read. The attempt fails finally, its capacity comes back, the
payload it was owed is resolved without being rendered, its outcome is written at the floor, and
the next pull moves on to whatever the schedule puts first. A generation started with
``attempt_deadline_ms`` does the same for itself when an attempt stays active longer than that,
on a durable timer that survives the worker that armed it.

A refusal arrives as an Update failure carrying one code from the protocol's closed set. Read
it with :func:`protocol_error_code`; anything that function returns ``None`` for is a fault
and not a protocol answer. :meth:`StreamHandle.stream_state` is harness-only and writes
nothing, and so is :meth:`StreamWorkflow.attempt_records`, which answers with one
:class:`~shogym.serve.protocol_v2.kernel.messages.AttemptRecord` per attempt: its positions, its
filing, its score or the ending it got instead, which of its messages were handed to the
transport, and whether a payload was owed against it at all.
:mod:`shogym.serve.protocol_v2.reader` is that Query read from a run directory.
"""

from shogym.serve.protocol_v2 import BlobRef, blob_ref
from shogym.serve.protocol_v2.kernel.activities import (
    fork_activities,
    fork_availability_activity,
    fork_preparation_activity,
    generate_payload_bundle_activity,
    grade_attempt_activity,
    kernel_activities,
    seal_attempt_activity,
    start_fork_child_activity,
    verify_blobs_activity,
    verify_fork_origin_activity,
)
from shogym.serve.protocol_v2.kernel.messages import (
    ABANDONED,
    ABANDONED_REASONS,
    CARRIER_SCHEMA_VERSIONS,
    CHECKPOINT_MANIFEST_SCHEMA_VERSION,
    CHILD_EXISTENCE,
    CHILD_READY_SCHEMA_VERSION,
    CONFIRMED_EXISTING,
    EXISTENCE_UNCONFIRMED,
    EXPIRED_PREPARATION,
    FORK_ABANDONED,
    FORK_CHILDREN_CONFIRMED,
    FORK_COMPLETE,
    FORK_CONFIGURATION_VIOLATION,
    FORK_CONFLICTED,
    FORK_CONTRACT_DRIFT,
    FORK_IN_FLIGHT,
    FORK_INTERRUPTED_COPY,
    FORK_INVALID_CHECKPOINT,
    FORK_MOVED_EXECUTION,
    FORK_NOT_QUIET,
    FORK_ORIGIN_DISAGREEMENT,
    FORK_PREPARED,
    FORK_REPAIRABLE_ABSENCE,
    FORK_REQUEST_CONFLICT,
    FORK_UNDECLARED_BRANCH,
    FORK_UNREADABLE_PARENT,
    FORK_UNRECOVERABLE_EVIDENCE,
    FORK_WITNESS_MISMATCH,
    FORK_WRONG_SOURCE,
    NEVER_ATTEMPTED,
    PROVEN_ABSENT,
    SPENT_RECOVERY_RESERVE,
    FORK_CARRIER_SCHEMA_VERSION,
    FORK_CHILD_COUNT,
    FORK_EXPIRED_AUTHORITY,
    FORK_ORIGIN_SCHEMA_VERSION,
    FORK_RECEIPT_SCHEMA_VERSION,
    FORK_REQUEST_SCHEMA_VERSION,
    FORK_AVAILABILITY_STEP,
    FORK_CLAIM_STEP,
    FORK_ORIGIN_STEP,
    FORK_PREPARATION_STEP,
    FORK_REFUSALS,
    FORK_START_STEP,
    FORK_STATUSES,
    FORK_STEPS,
    LEGACY_CARRIER_SCHEMA_VERSION,
    PERMANENT_FORK_REFUSALS,
    RETRYABLE_FORK_REFUSALS,
    NUMERIC_CONVERSION_VERSION,
    PREPARED_FORK_SCHEMA_VERSION,
    RECEIPT_CARRIER_SCHEMA_VERSION,
    RUN_ID_CEILING_BYTES,
    AnsweredUpdate,
    CheckpointComponent,
    CheckpointEvidence,
    CheckpointEvidenceAnswer,
    CheckpointManifest,
    ChildReady,
    ForkAvailability,
    ForkAvailabilityInput,
    ForkChildPlan,
    ForkChildReceipt,
    ForkChildStarted,
    ForkOriginVerified,
    ForkPreparation,
    ForkPreparationInput,
    ForkReceipt,
    ForkRequest,
    ForkStatusAnswer,
    ForkStatusQuestion,
    StartForkChildInput,
    VerifyForkOriginInput,
    PreparedChild,
    PreparedFork,
    SettledHarness,
    DEADLINE,
    FINAL_FAILURE_REASONS,
    FINAL_FAILURES,
    SEAL_FAILED,
    SEAL_UNUSABLE,
    STEP_CAP,
    AttemptFinalized,
    AttemptRecord,
    BlobsVerified,
    ConsumerClaim,
    ConsumerReceipt,
    EnvironmentCall,
    EnvironmentLease,
    FinalizeRequest,
    ForkOrigin,
    GeneratePayloadBundleInput,
    GenerationRecords,
    GradeAttemptInput,
    GradeAttemptResult,
    LineageOrigin,
    OfferedMessage,
    OperationFailure,
    OwnershipClaim,
    OwnershipReceipt,
    PayloadBundle,
    PayloadCandidate,
    PayloadCandidateResult,
    PresentedMessage,
    QueueClosed,
    SealAttemptInput,
    SealAttemptResult,
    SealRequest,
    SelectedSourceReference,
    SourceOriginContext,
    StartDifference,
    SourceProvenance,
    CarriedProjection,
    StreamCarry,
    StreamOutcome,
    StreamStart,
    StreamState,
    TaskItem,
    TerminalTool,
    VerifyBlobsInput,
    Writer,
    OPERATION_OUTCOMES,
    OPERATION_PHASES,
    OPERATION_REASONS,
    assignments_for,
    carrier_version,
    check_checkpoint_evidence,
    check_checkpoint_manifest,
    check_child_configuration,
    check_child_ready,
    check_complete_start_authorization,
    check_fork_origin,
    check_fork_receipt,
    check_fork_request,
    check_prepared_fork,
    answer_window_ends,
    check_receipt_within_bound,
    check_start_classification,
    check_transmitted_size,
    checkpoint_manifest_reference,
    child_blob_root,
    child_workflow_id,
    complete_start_digest,
    configuration_hash,
    continuation_argument,
    derived_selection,
    finalize_request_identity,
    fork_configuration,
    fork_preparation_operation_identity,
    fork_activity_id,
    fork_answer_window_ends,
    fork_receipt_bound,
    fork_request_digest,
    hidden_seal_id,
    origin_digest,
    ownership_claim_operation_identity,
    source_seal_id,
    start_difference_projection,
    unpack_carrier,
    verified_set_digest,
)
from shogym.serve.protocol_v2.kernel.runtime import (
    STREAM_TASK_QUEUE,
    TEMPORAL_ADDRESS_ENV,
    StreamHandle,
    discard_stream,
    durable_client,
    fork_barrier_stands,
    fork_can_be_retried,
    fork_preparation_epoch,
    fork_refusal,
    fork_status,
    origin_unverified,
    fork_stream,
    protocol_error_code,
    refuse_a_carried_projection,
    resume_run_directory,
    resume_stream,
    run_stream_worker,
    start_stream,
    stream_replayer,
    stream_worker,
    temporal_home,
    turnover_pending,
)
from shogym.serve.protocol_v2.kernel.workflow import (
    FORK_ANSWER_WINDOW_MS,
    FORK_AUTHORITY_HORIZON_MS,
    FORK_BARRIER,
    FORK_PREPARATION_BOUND_MS,
    FORK_RESERVE,
    FORK_RETENTION_FLOOR_MS,
    FORK_RETENTION_MARGIN_MS,
    FORKED,
    ORIGIN_UNVERIFIED,
    TURNOVER_PAYLOAD_CEILING_BYTES,
    TURNOVER_PENDING,
    TURNOVER_TRIGGER,
    ChildSelection,
    ForkBarrier,
    ForkRefused,
    OriginUnverified,
    StreamProtocolError,
    StreamWorkflow,
    TurnoverPending,
    child_carrier,
    transformed_child_counters,
    transformed_child_selection,
)

__all__ = [
    "ABANDONED",
    "CARRIER_SCHEMA_VERSIONS",
    "FORK_CARRIER_SCHEMA_VERSION",
    "FORK_ORIGIN_SCHEMA_VERSION",
    "LEGACY_CARRIER_SCHEMA_VERSION",
    "RECEIPT_CARRIER_SCHEMA_VERSION",
    "SourceOriginContext",
    "SourceProvenance",
    "OperationFailure",
    "OPERATION_OUTCOMES",
    "OPERATION_PHASES",
    "OPERATION_REASONS",
    "carrier_version",
    "continuation_argument",
    "derived_selection",
    "fork_configuration",
    "transformed_child_selection",
    "transformed_child_counters",
    "child_carrier",
    "ChildSelection",
    "ForkOrigin",
    "StartDifference",
    "ABANDONED_REASONS",
    "CHECKPOINT_MANIFEST_SCHEMA_VERSION",
    "CHILD_EXISTENCE",
    "CHILD_READY_SCHEMA_VERSION",
    "FORK_CHILD_COUNT",
    "FORK_RECEIPT_SCHEMA_VERSION",
    "FORK_REQUEST_SCHEMA_VERSION",
    "FORK_STATUSES",
    "NUMERIC_CONVERSION_VERSION",
    "PREPARED_FORK_SCHEMA_VERSION",
    "RUN_ID_CEILING_BYTES",
    "CheckpointComponent",
    "CheckpointEvidence",
    "CheckpointEvidenceAnswer",
    "CheckpointManifest",
    "ChildReady",
    "ForkAvailability",
    "ForkAvailabilityInput",
    "ForkChildPlan",
    "ForkChildReceipt",
    "ForkChildStarted",
    "ForkOriginVerified",
    "ForkPreparation",
    "ForkPreparationInput",
    "ForkReceipt",
    "ForkRequest",
    "ForkStatusAnswer",
    "ForkStatusQuestion",
    "StartForkChildInput",
    "VerifyForkOriginInput",
    "CONFIRMED_EXISTING",
    "EXISTENCE_UNCONFIRMED",
    "EXPIRED_PREPARATION",
    "NEVER_ATTEMPTED",
    "PROVEN_ABSENT",
    "SPENT_RECOVERY_RESERVE",
    "FORK_ABANDONED",
    "FORK_CHILDREN_CONFIRMED",
    "FORK_COMPLETE",
    "FORK_CONFIGURATION_VIOLATION",
    "FORK_CONFLICTED",
    "FORK_IN_FLIGHT",
    "FORK_INTERRUPTED_COPY",
    "FORK_INVALID_CHECKPOINT",
    "FORK_MOVED_EXECUTION",
    "FORK_NOT_QUIET",
    "FORK_ORIGIN_DISAGREEMENT",
    "FORK_PREPARED",
    "FORK_REPAIRABLE_ABSENCE",
    "FORK_CONTRACT_DRIFT",
    "FORK_REQUEST_CONFLICT",
    "FORK_UNDECLARED_BRANCH",
    "FORK_UNREADABLE_PARENT",
    "FORK_UNRECOVERABLE_EVIDENCE",
    "FORK_WITNESS_MISMATCH",
    "FORK_WRONG_SOURCE",
    "FORK_AVAILABILITY_STEP",
    "FORK_CLAIM_STEP",
    "FORK_EXPIRED_AUTHORITY",
    "FORK_ORIGIN_STEP",
    "FORK_PREPARATION_STEP",
    "FORK_REFUSALS",
    "FORK_START_STEP",
    "FORK_STEPS",
    "PERMANENT_FORK_REFUSALS",
    "RETRYABLE_FORK_REFUSALS",
    "fork_activities",
    "fork_activity_id",
    "fork_availability_activity",
    "fork_preparation_activity",
    "start_fork_child_activity",
    "verify_fork_origin_activity",
    "PreparedChild",
    "PreparedFork",
    "SettledHarness",
    "check_checkpoint_evidence",
    "check_checkpoint_manifest",
    "check_child_configuration",
    "check_child_ready",
    "check_complete_start_authorization",
    "check_fork_origin",
    "check_fork_receipt",
    "check_fork_request",
    "check_prepared_fork",
    "check_receipt_within_bound",
    "check_start_classification",
    "check_transmitted_size",
    "checkpoint_manifest_reference",
    "child_blob_root",
    "child_workflow_id",
    "complete_start_digest",
    "fork_receipt_bound",
    "fork_request_digest",
    "origin_digest",
    "start_difference_projection",
    "unpack_carrier",
    "verified_set_digest",
    "fork_preparation_operation_identity",
    "ownership_claim_operation_identity",
    "source_seal_id",
    "AnsweredUpdate",
    "DEADLINE",
    "FINAL_FAILURES",
    "FINAL_FAILURE_REASONS",
    "SEAL_FAILED",
    "SEAL_UNUSABLE",
    "STEP_CAP",
    "STREAM_TASK_QUEUE",
    "TEMPORAL_ADDRESS_ENV",
    "FORK_ANSWER_WINDOW_MS",
    "FORK_AUTHORITY_HORIZON_MS",
    "FORK_BARRIER",
    "FORK_PREPARATION_BOUND_MS",
    "FORK_RESERVE",
    "FORK_RETENTION_FLOOR_MS",
    "FORK_RETENTION_MARGIN_MS",
    "FORKED",
    "ForkBarrier",
    "ForkRefused",
    "answer_window_ends",
    "fork_answer_window_ends",
    "fork_barrier_stands",
    "fork_can_be_retried",
    "fork_preparation_epoch",
    "fork_refusal",
    "fork_status",
    "origin_unverified",
    "fork_stream",
    "ORIGIN_UNVERIFIED",
    "TURNOVER_PAYLOAD_CEILING_BYTES",
    "TURNOVER_PENDING",
    "TURNOVER_TRIGGER",
    "AttemptFinalized",
    "AttemptRecord",
    "BlobRef",
    "BlobsVerified",
    "ConsumerClaim",
    "ConsumerReceipt",
    "EnvironmentCall",
    "EnvironmentLease",
    "FinalizeRequest",
    "GeneratePayloadBundleInput",
    "GenerationRecords",
    "GradeAttemptInput",
    "GradeAttemptResult",
    "LineageOrigin",
    "OfferedMessage",
    "OriginUnverified",
    "OwnershipClaim",
    "OwnershipReceipt",
    "PayloadBundle",
    "PayloadCandidate",
    "PayloadCandidateResult",
    "PresentedMessage",
    "QueueClosed",
    "SealAttemptInput",
    "SealAttemptResult",
    "SealRequest",
    "SelectedSourceReference",
    "CarriedProjection",
    "StreamCarry",
    "StreamHandle",
    "StreamOutcome",
    "StreamProtocolError",
    "StreamStart",
    "StreamState",
    "StreamWorkflow",
    "TaskItem",
    "TerminalTool",
    "TurnoverPending",
    "VerifyBlobsInput",
    "Writer",
    "assignments_for",
    "blob_ref",
    "configuration_hash",
    "discard_stream",
    "durable_client",
    "generate_payload_bundle_activity",
    "grade_attempt_activity",
    "finalize_request_identity",
    "hidden_seal_id",
    "kernel_activities",
    "protocol_error_code",
    "refuse_a_carried_projection",
    "resume_run_directory",
    "resume_stream",
    "run_stream_worker",
    "seal_attempt_activity",
    "start_stream",
    "stream_replayer",
    "stream_worker",
    "temporal_home",
    "turnover_pending",
    "verify_blobs_activity",
]
